#!/usr/bin/env bash
# ANKA OS — First-Run Setup Wizard
# Uses kdialog for a native KDE/Wayland dialog experience.
# Runs once per user; creates ~/.anka-setup-done on completion.

set -euo pipefail

SENTINEL="$HOME/.anka-setup-done"
anka_CONFIG="$HOME/.config/anka/setup.conf"
LOG_FILE="$HOME/.config/anka/first-run.log"

# ── Guard: exit immediately if already set up ────────────────────────────────
if [[ -f "$SENTINEL" ]]; then
  exit 0
fi

mkdir -p "$HOME/.config/anka"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

log "ANKA first-run wizard started"

# ── Helper: show an error and exit ──────────────────────────────────────────
die() {
  kdialog --title "ANKA OS — Error" --error "$1" 2>/dev/null || true
  log "ERROR: $1"
  exit 1
}

# ── STEP 0: Welcome ──────────────────────────────────────────────────────────
kdialog \
  --title "ANKA OS — Welcome / Hoş Geldiniz" \
  --msgbox "Welcome to ANKA OS!\n\nThis short wizard will personalise your system.\nIt only runs once.\n\n───\n\nANKA OS'e Hoş Geldiniz!\n\nBu kısa sihirbaz sisteminizi kişiselleştirecek.\nYalnızca bir kez çalışır." \
  2>/dev/null

# ── STEP 1: Language selection / Dil seçimi ─────────────────────────────────
LANG_CHOICE=$(kdialog \
  --title "ANKA OS — Language / Dil" \
  --combobox "Select your preferred language:\nTercih ettiğiniz dili seçin:" \
  "English" "Türkçe" \
  --default "English" \
  2>/dev/null) || die "Language selection cancelled."

log "Language selected: $LANG_CHOICE"

if [[ "$LANG_CHOICE" == "Türkçe" ]]; then
  LOCALE="tr_TR.UTF-8"
  MSG_USECASE="ANKA OS'i ne için kullanacaksınız?"
  OPT_GAMING="Oyun (Gaming)"
  OPT_WORK="İş (Work)"
  OPT_BOTH="Her İkisi (Both)"
  MSG_AI="AI asistan kullanmak ister misiniz?"
  AI_FREE="Ücretsiz (Yerel Model)"
  AI_CLOUD="Cloud API Anahtarı ile"
  AI_SKIP="Hayır, teşekkürler"
  MSG_DONE="ANKA OS kurulumu tamamlandı!\n\nSisteminiiz kullanıma hazır."
  MSG_REBOOT="Değişikliklerin geçerli olması için oturumu yeniden başlatın."
  TITLE_USECASE="ANKA OS — Kullanım Amacı"
  TITLE_AI="ANKA OS — AI Asistan"
  TITLE_DONE="ANKA OS — Hazır!"
else
  LOCALE="en_US.UTF-8"
  MSG_USECASE="What will you use ANKA OS for?"
  OPT_GAMING="Gaming"
  OPT_WORK="Work / Productivity"
  OPT_BOTH="Both"
  MSG_AI="Would you like to enable an AI assistant?"
  AI_FREE="Yes — Free (Local Model)"
  AI_CLOUD="Yes — Cloud API Key"
  AI_SKIP="No, thanks"
  MSG_DONE="ANKA OS setup is complete!\n\nYour system is ready to use."
  MSG_REBOOT="Please log out and back in for all changes to take effect."
  TITLE_USECASE="ANKA OS — Use Case"
  TITLE_AI="ANKA OS — AI Assistant"
  TITLE_DONE="ANKA OS — Ready!"
fi

# Write locale preference
echo "LOCALE=$LOCALE" >> "$anka_CONFIG"

# Apply locale for the current user (home-manager rebuild picks this up later)
if command -v localectl &>/dev/null; then
  localectl set-locale "LANG=$LOCALE" 2>/dev/null || true
fi
log "Locale set to: $LOCALE"

# ── STEP 2: Use-case selection ───────────────────────────────────────────────
USECASE=$(kdialog \
  --title "$TITLE_USECASE" \
  --combobox "$MSG_USECASE" \
  "$OPT_GAMING" "$OPT_WORK" "$OPT_BOTH" \
  --default "$OPT_BOTH" \
  2>/dev/null) || die "Use-case selection cancelled."

log "Use case selected: $USECASE"
echo "USECASE=$USECASE" >> "$anka_CONFIG"

# ── Install packages based on use case ──────────────────────────────────────
install_packages() {
  local packages=("$@")
  if command -v nix-env &>/dev/null; then
    log "Installing packages: ${packages[*]}"
    nix-env -iA "${packages[@]}" 2>>"$LOG_FILE" || {
      log "WARN: nix-env install failed — packages may need nixos-rebuild"
    }
  fi
}

GAMING_ENABLED=false
WORK_ENABLED=false

case "$USECASE" in
  "$OPT_GAMING")
    GAMING_ENABLED=true
    ;;
  "$OPT_WORK")
    WORK_ENABLED=true
    ;;
  "$OPT_BOTH")
    GAMING_ENABLED=true
    WORK_ENABLED=true
    ;;
esac

echo "GAMING_ENABLED=$GAMING_ENABLED" >> "$anka_CONFIG"
echo "WORK_ENABLED=$WORK_ENABLED"    >> "$anka_CONFIG"

# Write a NixOS user overlay for the chosen packages
NIXOS_EXTRA_CONFIG="$HOME/.config/anka/extra-packages.nix"

{
  echo "# Auto-generated by anka-first-run wizard — do not edit manually"
  echo "{ pkgs, ... }: {"
  echo "  environment.systemPackages = with pkgs; ["
  if [[ "$GAMING_ENABLED" == "true" ]]; then
    echo "    # Gaming"
    echo "    steam"
    echo "    lutris"
    echo "    bottles"
    echo "    gamemode"
    echo "    mangohud"
    echo "    heroic"
  fi
  if [[ "$WORK_ENABLED" == "true" ]]; then
    echo "    # Productivity"
    echo "    libreoffice-qt6-fresh"
    echo "    onlyoffice-bin"
    echo "    thunderbird"
    echo "    obsidian"
  fi
  echo "  ];"

  if [[ "$GAMING_ENABLED" == "true" ]]; then
    echo "  # GE-Proton via steam-run"
    echo "  programs.steam = {"
    echo "    enable = true;"
    echo "    gamescopeSession.enable = true;"
    echo "  };"
    echo "  programs.gamemode.enable = true;"
  fi

  echo "}"
} > "$NIXOS_EXTRA_CONFIG"

log "Extra package config written to: $NIXOS_EXTRA_CONFIG"

# ── STEP 3: AI assistant ─────────────────────────────────────────────────────
AI_CHOICE=$(kdialog \
  --title "$TITLE_AI" \
  --combobox "$MSG_AI" \
  "$AI_FREE" "$AI_CLOUD" "$AI_SKIP" \
  --default "$AI_FREE" \
  2>/dev/null) || die "AI assistant selection cancelled."

log "AI choice: $AI_CHOICE"
echo "AI_CHOICE=$AI_CHOICE" >> "$anka_CONFIG"

case "$AI_CHOICE" in
  "$AI_CLOUD")
    API_KEY=$(kdialog \
      --title "$TITLE_AI" \
      --password "Enter your Anthropic API key (claude.ai/account):" \
      2>/dev/null) || true

    if [[ -n "$API_KEY" ]]; then
      # Store securely in the user keyring via secret-tool if available,
      # otherwise write to a 0600 env file
      if command -v secret-tool &>/dev/null; then
        echo -n "$API_KEY" | secret-tool store \
          --label="ANKA AI API Key" \
          service anka-ai username api-key 2>/dev/null || true
        log "API key stored in keyring"
      else
        APIKEY_FILE="$HOME/.config/anka/api.env"
        echo "ANTHROPIC_API_KEY=$API_KEY" > "$APIKEY_FILE"
        chmod 600 "$APIKEY_FILE"
        log "API key written to $APIKEY_FILE (mode 600)"
      fi

      echo "AI_MODE=cloud" >> "$anka_CONFIG"
    else
      echo "AI_MODE=none"  >> "$anka_CONFIG"
    fi
    ;;

  "$AI_FREE")
    echo "AI_MODE=local" >> "$anka_CONFIG"
    log "Local AI model selected (ollama will be enabled on next rebuild)"
    ;;

  *)
    echo "AI_MODE=none" >> "$anka_CONFIG"
    log "AI assistant skipped"
    ;;
esac

# ── STEP 4: Done ─────────────────────────────────────────────────────────────
kdialog \
  --title "$TITLE_DONE" \
  --msgbox "$MSG_DONE\n\n$MSG_REBOOT" \
  2>/dev/null

log "Wizard completed successfully"

# Create sentinel file — prevents the wizard from running again
touch "$SENTINEL"
log "Sentinel created: $SENTINEL"

exit 0