# ANKA OS — default host configuration
# This file is the top-level NixOS module for a generic desktop/gaming PC.
# For a real machine, copy this to hosts/<hostname>/configuration.nix and
# import a hardware-configuration.nix generated by nixos-generate-config.
{ config, lib, pkgs, inputs, ... }:

{
  imports = [
    # ── System base ───────────────────────────────────────────────────────
    ../../modules/system/boot.nix
    ../../modules/system/kernel.nix
    ../../modules/system/filesystem.nix
    ../../modules/system/network.nix
    ../../modules/system/security.nix

    # ── Desktop + media ───────────────────────────────────────────────────
    ../../modules/desktop

    # ── Gaming ────────────────────────────────────────────────────────────
    ../../modules/gaming

    # ── GPU drivers ───────────────────────────────────────────────────────
    ../../modules/gpu

    # ── Applications ──────────────────────────────────────────────────────
    ../../modules/apps

    # ── Phase 2: AI layer ─────────────────────────────────────────────────
    ../../modules/ai

    # ── Phase 2: Performance tuning ───────────────────────────────────────
    ../../modules/performance

    # ── Phase 2: Windows & media compatibility ────────────────────────────
    ../../modules/compat/windows.nix
    ../../modules/compat/media.nix

    # ── Phase 2: Accessibility ────────────────────────────────────────────
    ../../modules/accessibility

    # ── Update system ─────────────────────────────────────────────────────
    ../../modules/update/default.nix
    ../../modules/update/version.nix
  ];

  # ═══════════════════════════════════════════════════════════════════════
  # ANKA module options
  # ═══════════════════════════════════════════════════════════════════════

  # ── Boot ──────────────────────────────────────────────────────────────
  anka.boot.loader   = "systemd-boot";
  anka.boot.plymouth = true;
  anka.boot.timeout  = 3;

  # ── Kernel ────────────────────────────────────────────────────────────
  anka.kernel.variant = "cachyos-bore";

  # ── Filesystem ────────────────────────────────────────────────────────
  anka.filesystem.rootFormat       = "btrfs";
  anka.filesystem.btrfsSubvolumes  = true;
  anka.filesystem.tmpOnTmpfs       = true;

  # ── Network ───────────────────────────────────────────────────────────
  anka.network.hostname   = "anka";
  anka.network.manager    = "networkmanager";
  anka.network.mdns       = true;
  anka.network.bluetooth  = true;

  # ── Security ──────────────────────────────────────────────────────────
  anka.security.enable              = true;
  anka.security.firewall.enable     = true;
  anka.security.firewall.allowSsh   = false;  # no SSH by default on desktop
  anka.security.apparmor.enable     = true;
  anka.security.fail2ban.enable     = false;  # only needed when SSH is open
  anka.security.kernelHardening     = true;

  # ── Desktop ───────────────────────────────────────────────────────────
  anka.desktop.enable              = true;
  anka.desktop.session             = "plasma6";
  anka.desktop.wayland             = true;
  anka.desktop.autoLogin.enable    = false;
  anka.desktop.extraApps           = true;

  # ── GPU — change to "nvidia" or "intel+nvidia" for your hardware ──────
  anka.gpu.type = "amd";

  # ── Gaming ────────────────────────────────────────────────────────────
  anka.gaming.enable            = true;
  anka.gaming.steam.enable      = true;
  anka.gaming.gamescope.enable  = true;
  anka.gaming.lutris            = true;
  anka.gaming.heroic            = true;
  anka.gaming.discord           = true;

  # ── Applications ──────────────────────────────────────────────────────
  anka.apps.enable    = true;
  anka.apps.flatpak   = true;
  anka.apps.terminal  = "konsole";
  anka.apps.browser   = "firefox";

  # ── AI layer ──────────────────────────────────────────────────────────
  anka.ai.enable        = true;
  anka.ai.localModel    = "qwen2.5:7b";
  anka.ai.enableVoice   = true;
  anka.ai.whisperModel  = "base";
  anka.ai.mcp.enable    = true;

  # ── Performance ───────────────────────────────────────────────────────
  anka.performance.enable           = true;
  anka.performance.zram.enable      = true;
  anka.performance.zram.algorithm   = "lz4";
  anka.performance.zram.memoryPercent = 50;
  anka.performance.governor         = "schedutil";
  anka.performance.thp              = "madvise";
  anka.performance.enableEarlyoom   = true;
  anka.performance.gaming.enable    = true;
  anka.performance.gaming.realtimeAudio = true;
  anka.performance.gaming.amdTweaks     = true;

  # ── Windows compatibility ─────────────────────────────────────────────
  anka.compat.windows.enable        = true;
  anka.compat.windows.geProton.enable = true;
  anka.compat.windows.umuLauncher   = true;
  anka.compat.windows.protontricks  = true;
  anka.compat.windows.bottles       = true;
  anka.compat.windows.ntfs.enable   = true;
  anka.compat.windows.ntfs.driver   = "ntfs-3g";

  # ── Media codecs ──────────────────────────────────────────────────────
  anka.compat.media.enable          = true;
  anka.compat.media.dvd             = true;
  anka.compat.media.hardwareDecode  = true;
  anka.compat.media.vaapi           = true;
  anka.compat.media.extraPlayers    = true;

  # ── Accessibility ─────────────────────────────────────────────────────
  anka.accessibility.enable  = false;  # opt-in; enable per-user if needed
  # anka.accessibility.orca  = true;
  # anka.accessibility.largeFonts = true;

  # ── Update system ─────────────────────────────────────────────────────
  anka.update.enable   = true;
  anka.update.channel  = "stable";
  anka.update.autoApply = false;  # notify-only; user triggers update via KCM

  # ═══════════════════════════════════════════════════════════════════════
  # Host-level NixOS settings
  # ═══════════════════════════════════════════════════════════════════════

  # ── Primary user (override per-host) ─────────────────────────────────
  users.users.anka = {
    isNormalUser  = true;
    description   = "ANKA User";
    extraGroups   = [
      "wheel"          # sudo
      "networkmanager" # NM without password
      "video"          # GPU / DRI access
      "audio"          # audio (PipeWire)
      "gamemode"       # GameMode
      "anka-mcp"       # MCP server access (for AI daemon)
    ];
    initialPassword = "anka";   # CHANGE AFTER FIRST LOGIN
  };

  # ── Home Manager — user-level configuration ───────────────────────────
  home-manager = {
    useGlobalPkgs   = true;
    useUserPackages = true;
    users.anka    = import ./home.nix;
  };

  # ── Nixpkgs ───────────────────────────────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── State version — do NOT change after first install ────────────────
  system.stateVersion = "24.11";
}